### ISSUE TITLE
Trying to build using wxwidgets 3.0.4

### ISSUE THREAD

**Issue by DrEdHepler** [wxFormBuilder/wxFormBuilder#403]
I'm trying to build wxformbuilder (3.6.2) using wxWidgets 3.0.4

I had to edit "wxwidgets.lua" to make the wxTarget be gtk3.

Everything compiles, but when linking wxFormBuilder the linker throws the error:

//lib/libwx_gtk2u_stc-3.0.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@WXU_3.0'

It appears that the .d files in the .../gmake/obj/Release/wxFormBuilder directory still refer to gtk2

What configuration flags (or switch) needs to be changed to eliminate this error?

Thanks!!

**Comment by DrEdHepler** [comment]
Found that my wx-config was pointing to the wrong place...

However, after fixing that, I still get errors when linking wxFormBuilder.   They are:

Linking wxFormBuilder
obj/Release/wxFormBuilder/maingui.o:(.rodata._ZTV20wxMDIParentFrameBase[_ZTV20wxMDIParentFrameBase]+0x1f0): undefined reference to `wxWindow::IsShown() const'
obj/Release/wxFormBuilder/about.o:(.rodata._ZTV19wxNavigationEnabledI8wxWindowE[_ZTV19wxNavigationEnabledI8wxWindowE]+0x1f0): undefined reference to `wxWindow::IsShown() const'
obj/Release/wxFormBuilder/about.o:(.rodata._ZTV10wxScrolledI7wxPanelE[_ZTV10wxScrolledI7wxPanelE]+0x1f0): undefined reference to `wxWindow::IsShown() const'
obj/Release/wxFormBuilder/about.o:(.rodata._ZTV11AboutDialog[_ZTV11AboutDialog]+0x1f0): undefined reference to `wxWindow::IsShown() const'
obj/Release/wxFormBuilder/about.o:(.rodata._ZTV10HtmlWindow[_ZTV10HtmlWindow]+0x1f0): undefined reference to `wxWindow::IsShown() const'
obj/Release/wxFormBuilder/genericpanel.o:(.rodata._ZTV13GenericWindow[_ZTV13GenericWindow]+0x1f0): more undefined references to `wxWindow::IsShown() const' follow
collect2: error: ld returned 1 exit status
make[1]: *** [../../../output/bin/wxformbuilder] Error 1
make: *** [wxFormBuilder] Error 2

Has something changed between 3.0.2 and 3.0.4 that causes this, or did I do something wrong?

Thanks!!

**Comment by jhasse** [comment]
> I had to edit "wxwidgets.lua" to make the wxTarget be gtk3.

Hm ... that shouldn't be needed.

Which operation system are you trying this on?

btw: Please post the output on GitHub inside backticks:
````
Normal text.

```
code goes here
```
````
