### ISSUE TITLE
Ubuntu 20.04.3 LTS system unable to build at hash 8577934fffcb

### ISSUE THREAD

**Issue by Cudaman** [wxFormBuilder/wxFormBuilder#700]
Newbie here, 
I just started working with wxFormBuilder a couple of weeks ago.  At that time I was able to build on my Ubuntu 20.04.3 LTS with no issues.  Last night I pulled from the tip and encountered the following linker errors:

```
/usr/bin/ld: wxformbuilder@exe/src_codegen_cppcg.cpp.o: in function `CppCodeGenerator::GenerateCode(std::shared_ptr<ObjectBase>)':
cppcg.cpp:(.text+0x17f32): undefined reference to `getVersion()'
/usr/bin/ld: wxformbuilder@exe/src_codegen_luacg.cpp.o: in function `LuaCodeGenerator::GenerateCode(std::shared_ptr<ObjectBase>)':
luacg.cpp:(.text+0x14d41): undefined reference to `getVersion()'
/usr/bin/ld: wxformbuilder@exe/src_codegen_phpcg.cpp.o: in function `PHPCodeGenerator::GenerateCode(std::shared_ptr<ObjectBase>)':
phpcg.cpp:(.text+0x10629): undefined reference to `getVersion()'
/usr/bin/ld: wxformbuilder@exe/src_codegen_pythoncg.cpp.o: in function `PythonCodeGenerator::GenerateCode(std::shared_ptr<ObjectBase>)':
pythoncg.cpp:(.text+0x14c9c): undefined reference to `getVersion()'
/usr/bin/ld: wxformbuilder@exe/src_maingui.cpp.o: in function `MyApp::OnRun()':
maingui.cpp:(.text+0x1ab1): undefined reference to `getVersion()'
/usr/bin/ld: wxformbuilder@exe/src_rad_mainframe.cpp.o:mainframe.cpp:(.text+0x3e5c): more undefined references to `getVersion()' follow
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```
Since that time, I've narrowed the transition to hash 8577934fffcb.  Based on the changes at that hash, I'm guessing that the build requires a minimum revision of CMake.  My current version of CMake is 3.16.3.

If a minimum version of CMake has been introduced with these changes, can that be published as part of the build instructions?

**Comment by sodevel** [comment]
Congratulations, you got me. I was quite in a hurry yesterday because i wanted to get some things done, i discovered too late that my changes break the build with PreMake and Meson. I'm going to fix that, it will be ugly, but it will work.

I hope i can release a new version soon, this one will use CMake as its primary build system, the CI and myself are using it right now. The CMake build is already fully working, however you need the very recent CMake version 3.21, this isn't available as package for your system currently. You need to install from source, but this is very easy because it doesn't have any dependencies.

A bigger problem for you is that the CMake build currently requires wxWidgets 3.1.2 which isn't available on any Ubuntu release, at least not as official package. I think this isn't a hard dependency, it should still compile with wxWidgets 3.0.x, but these older releases cause some issues in wxFormBuilder and all other platforms offer wxWidgets 3.1.x releases now. Maybe i add an option to allow building with the older release as last resort.

**Comment by Cudaman** [comment]
Thanks for your swift response.  Closing issue.
