### ISSUE TITLE
Unable to build on Win10

### ISSUE THREAD

**Issue by PaowZ** [wxFormBuilder/wxFormBuilder#769]
Hi,

Just following the build steps from documentation and ending up with a link error related to **libbfd**.a library. Some symbols are no longer provided by this lib or is it a wrong version ?

Below the output:

`
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
xx-x86.o):(.text+0x95b): undefined reference to `sframe_encoder_write'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
xx-x86.o):(.text+0x990): undefined reference to `sframe_encoder_free'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
xx-x86.o):(.text+0xaaa): undefined reference to `sframe_encode'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
xx-x86.o):(.text+0xab8): undefined reference to `sframe_calc_fre_type'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
xx-x86.o):(.text+0xac3): undefined reference to `sframe_fde_create_func_info'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
xx-x86.o):(.text+0xb3f): undefined reference to `sframe_fde_create_func_info'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
xx-x86.o):(.text+0xb5f): undefined reference to `sframe_encoder_add_funcdesc'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
xx-x86.o):(.text+0xb9a): undefined reference to `sframe_encoder_add_fre'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
xx-x86.o):(.text+0xbc6): undefined reference to `sframe_encoder_add_funcdesc'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
xx-x86.o):(.text+0xc0f): undefined reference to `sframe_encoder_add_fre'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
-sframe.o):(.text+0x13c): undefined reference to `sframe_decode'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
-sframe.o):(.text+0x151): undefined reference to `sframe_decoder_get_num_fidx'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
-sframe.o):(.text+0x266): undefined reference to `sframe_decoder_free'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
-sframe.o):(.text+0x2c8): undefined reference to `sframe_decoder_get_num_fidx'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
-sframe.o):(.text+0x4d3): undefined reference to `sframe_decoder_get_abi_arch'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
-sframe.o):(.text+0x4dd): undefined reference to `sframe_encoder_get_abi_arch'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
-sframe.o):(.text+0x4f2): undefined reference to `sframe_decoder_get_num_fidx'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
-sframe.o):(.text+0x500): undefined reference to `sframe_encoder_get_num_fidx'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
-sframe.o):(.text+0x5a7): undefined reference to `sframe_decoder_get_funcdesc'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
-sframe.o):(.text+0x5fc): undefined reference to `sframe_decoder_get_hdr_size'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
-sframe.o):(.text+0x689): undefined reference to `sframe_encoder_add_funcdesc'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
-sframe.o):(.text+0x6dd): undefined reference to `sframe_decoder_get_fre'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
-sframe.o):(.text+0x6ef): undefined reference to `sframe_encoder_add_fre'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
-sframe.o):(.text+0x732): undefined reference to `sframe_decoder_free'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
-sframe.o):(.text+0x916): undefined reference to `sframe_decoder_get_abi_arch'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
-sframe.o):(.text+0x925): undefined reference to `sframe_decoder_get_fixed_fp_offset'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
-sframe.o):(.text+0x934): undefined reference to `sframe_decoder_get_fixed_ra_offset'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
-sframe.o):(.text+0x965): undefined reference to `sframe_encode'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
-sframe.o):(.text+0xa16): undefined reference to `sframe_encoder_write'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(elf
-sframe.o):(.text+0xa4a): undefined reference to `sframe_encoder_free'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(com
press.o):(.text+0x175): undefined reference to `ZSTD_decompress'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(com
press.o):(.text+0x17d): undefined reference to `ZSTD_isError'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(com
press.o):(.text+0x1103): undefined reference to `ZSTD_compress'
D:/_data/tools/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/_data/tools/msys2/mingw64/lib/libbfd.a(com
press.o):(.text+0x110e): undefined reference to `ZSTD_isError'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/wxFormBuilder_app.dir/build.make:915: stage/wxFormBuilder.exe] Error 1
make[1]: *** [CMakeFiles/Makefile2:239: src/CMakeFiles/wxFormBuilder_app.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
`

Any clue would be greatly appreciated ! :-)

**Comment by sodevel** [comment]
It looks like you are using a very recent GCC version and the dependencies of `libbfd` are changed. It looks like the library now links against `zstd` instead of or in addition to `zlib`.

I am not using MSYS2 myself and i don't know if the Virtual Environment on GitHub is already using this version so i can't test this quickly currently. If you want to test that yourself, you need to modify `third_party/stack_trace/CMakeLists.txt`.

**Comment by sodevel** [comment]
I just triggered a build on GitHub and although GCC 12.2.0 was used as well, the build succeeded. However, the binutils package (which contains libbfd) was still at version 2.39, the MSYS2 package registry already contains binutils 2.40. Looking at this diff https://github.com/msys2/MINGW-packages/commit/594c064fd4150f4fad50e1ec19f86af58e5357fd#diff-ba919a2b23a589f8f4269c92d25859f6453003528dfaec7c11169d50df80ed22, it seems that indeed zlib got replaced by zstd.

Since i do not know how to test which version of libbfd is present i don't want to change the CMakeLists file now, this would break building here on GitHub. I would wait until GitHub updates its environment.

**Comment by sodevel** [comment]
Apparently some of the GitHub Runners are already updated and use binutils 2.40 while others are still using binutils 2.39, it's pretty random which one you get. I did some tests, it's not just zstd that is required additionally but also sframe. I changed the CMake files so that the build works now with both binutils versions.

**Comment by sodevel** [comment]
Closing this as resolved
