### ISSUE TITLE
wxFALLTHROUGH’ was not declared in this scope

### ISSUE THREAD

**Issue by IamSierraCharlie** [wxFormBuilder/wxFormBuilder#429]
Hi,
Followed the instructions in Readme.md

```
git clone --recursive --depth=1 https://github.com/wxFormBuilder/wxFormBuilder
cd wxFormBuilder
./create_build_files4.sh
cd build/3.0/gmake
make config=release
```

Have the following error on Ubuntu 16.04

xrcpreview.cpp
annoyingdialog.cpp
encodingutils.cpp
filetocarray.cpp
stringutils.cpp
typeconv.cpp
wxfbipc.cpp
md5.cc
In file included from /usr/include/wx-3.0/wx/propgrid/propgrid.h:26:0,
                 from /usr/include/wx-3.0/wx/propgrid/manager.h:18,
                 from ../../../src/utils/../rad/inspector/objinspect.h:35,
                 from ../../../src/utils/typeconv.cpp:30:
/usr/include/wx-3.0/wx/propgrid/property.h: In member function ‘void wxPGChoices::Set(const wxArrayString&, const wxArrayInt&)’:
/usr/include/wx-3.0/wx/propgrid/property.h:1049:22: warning: the compiler can assume that the address of ‘values’ will always evaluate to ‘true’ [-Waddress]
         if ( &values )
                      ^
/usr/include/wx-3.0/wx/propgrid/property.h:1049:22: warning: the compiler can assume that the address of ‘values’ will always evaluate to ‘true’ [-Waddress]
../../../src/utils/typeconv.cpp: In function ‘void TypeConv::ParseBitmapWithResource(const wxString&, wxString*, wxString*, wxSize*)’:
../../../src/utils/typeconv.cpp:529:5: error: ‘wxFALLTHROUGH’ was not declared in this scope
     wxFALLTHROUGH;
     ^~~~~~~~~~~~~
wxFormBuilder.make:319: recipe for target 'obj/Release/wxFormBuilder/typeconv.o' failed
make[1]: *** [obj/Release/wxFormBuilder/typeconv.o] Error 1
make[1]: *** Waiting for unfinished jobs....
Makefile:44: recipe for target 'wxFormBuilder' failed
make: *** [wxFormBuilder] Error 2

I've installed this before without issue, but am doing this from scratch again.  I can't find anything relating to wxFALLTHROUGH’ was not declared in this scope type issue although I could be searching for the wrong thing... any ideas?

**Comment by jhasse** [comment]
It seems that `wxFALLTHROUGH` isn't available in your wxWidgets version. Can you try to replace it with `[[fallthrough]]` and if that doesn't work just remove it?

**Comment by IamSierraCharlie** [comment]
@jhasse 
Firstly, thank you so much for your prompt response - I thought I would be the only one at home on a Saturday night not out partying with friends :-D
Secondly, your suggestion was absoluteness spot on - in the end I used libwxgtk3.1-dev libwxgtk-media3.1-dev instead of 3.0.  I was unaware of the .1 increment.  After going through the process again with the updates, the compile and install worked without issue.
Thanks again!

**Comment by jhasse** [comment]
You're welcome. It's saturday morning were I live btw ;)

**Comment by DavidGriffith** [comment]
It looks like the change that provoked this issue is a3f139f5e20949e9a5a23cc954234a1bacdd10f2

**Comment by IamSierraCharlie** [comment]
Just to clarify, is there ever a time that wxFALLTHROUGH could work with the installation of libwxgtk3.0-dev libwxgtk-media3.0-dev?   As mentioned I upgraded to 3.1 to work around the issue; the other alternative was to omit this feature altogether.    Can you use wxFALLTHROUGH with those 3.0 versions or not at all?

**Comment by DavidGriffith** [comment]
@IamSierraCharlie Version 3.0.3 introduced the xvFALLTHROUGH define.  It can be fixed in a pinch by adding the following code to src/utils/typeconv.cpp:

```
#ifndef wxFALLTHROUGH
    #define wxFALLTHROUGH ((void)0)
#endif
```
I'm working on #440 to do this cleanly.
